version: 2

registries:
  nuget.org:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json
  dseinternational-nuget:
    type: nuget-feed
    url: https://www.myget.org/F/dseinternational/api/v3/index.json
    username: dseinternational
    password: ${{secrets.PACKAGES_TOKEN}}

updates:
  - package-ecosystem: nuget
    registries: "*"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:30"
      timezone: "Europe/London"
    open-pull-requests-limit: 20
    reviewers:
      - frankbuckley
    assignees:
      - frankbuckley

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:30"
      timezone: "Europe/London"
    open-pull-requests-limit: 20
    reviewers:
      - frankbuckley
    assignees:
      - frankbuckley

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:30"
      timezone: "Europe/London"
    open-pull-requests-limit: 20
    reviewers:
      - frankbuckley
    assignees:
      - frankbuckley
