name: PR Build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        image: ["mssql-server", "mssql-server-fts"]

    name: Build ${{ matrix.image }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # avoid shallow clone for version calculation

      - name: Docker login
        run: |
          docker login ghcr.io -u frankbuckley --password ${{ secrets.PACKAGES_TOKEN }}
        shell: pwsh

      - name: Set .NET SDK version
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.304"

      - name: Set Versions
        id: nbgv
        uses: dotnet/nbgv@master
        with:
          setCommonVars: true
          setAllVars: true

      - name: Diagnostics
        run: "Get-ChildItem Env:"
        shell: pwsh

      - name: Build Docker image
        run: |
          docker build ./src/${{ matrix.image }} `
            --tag ghcr.io/dseinternational/${{ matrix.image }}:latest `
            --tag ghcr.io/dseinternational/${{ matrix.image }}:${{ steps.nbgv.outputs.SemVer2 }} `
        shell: pwsh
